# This file configures the static analysis results for your project (errors,
# warnings, and lints).
#
# This enables the lint rules recommended by the Flutter team.
# See https://flutter.dev/docs/development/tools/linter#enabling-the-lints
#
# For a list of all available lints, see
# https://dart.dev/guides/language/analysis-options

include: package:flutter_lints/flutter.yaml

linter:
  # The lint rules are defined here. For a full list of available rules,
  # see the documentation page linked above.
  rules:
    # --- СТИЛЬ ---
    - always_declare_return_types
    - prefer_single_quotes
    - prefer_relative_imports
    - unnecessary_brace_in_string_interps
    - unnecessary_const
    - unnecessary_new
    - unnecessary_string_interpolations
    - prefer_final_locals
    - prefer_final_fields
    - use_key_in_widget_constructors

    # --- ЧИТАЕМОСТЬ И НАДЕЖНОСТЬ ---
    - avoid_print # Запрещает print в продакшен коде. Используйте logger.
    - avoid_unnecessary_containers
    - avoid_empty_else
    - avoid_returning_null_for_void
    - avoid_slow_async_io
    - avoid_types_on_closure_parameters
    - await_only_futures
    - cancel_subscriptions
    - control_flow_in_finally
    - empty_catches
    - no_logic_in_create_state
    - prefer_conditional_assignment
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_contains
    - prefer_for_elements_to_map_fromIterable
    - prefer_is_empty
    - prefer_is_not_empty
    - slash_for_doc_comments
    - valid_regexps
    # - package_api_docs # REMOVED: Deprecated lint rule
    - only_throw_errors # Запрещает throw "строк"
    - unawaited_futures # Предупреждает о Future, который не был дождан через await

    # --- ИМЕНОВАНИЕ ---
    - constant_identifier_names
    - non_constant_identifier_names
    - library_prefixes

    # --- БЕЗОПАСНОСТЬ И ОШИБКИ ---
    - literal_only_boolean_expressions
    - test_types_in_equals
    - throw_in_finally
    - unnecessary_getters_setters

    # --- ASYNC ---
    - avoid_void_async
    # REMOVED DUPLICATE: unawaited_futures (already on line 53)

# Additional config for excluding generated files from analysis
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/l10n/**"
  errors:
    # Treat specific issues as errors, warnings, or ignore them.
    # For example, to make missing required parameters an error:
    missing_required_param: error

    # Ignore deprecated API usage (SharePlus, Matrix transforms, etc.)
    deprecated_member_use: ignore

    # Ignore async file I/O warnings (acceptable for our use case)
    avoid_slow_async_io: ignore

    # Ignore BuildContext across async gaps (we handle it correctly)
    use_build_context_synchronously: ignore

    # Ignore unawaited futures in tests (intentional in some test cases)
    unawaited_futures: ignore

    # Ignore unused imports/elements in tests
    unused_import: ignore
    unused_element: ignore

    # Ignore print statements in tests
    avoid_print: ignore

    # Ignore missing return types in test helpers
    always_declare_return_types: ignore

