name: lifeline
description: Lifeline MVP
publish_to: "none"
version: 1.0.94+94


environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # --- FIREBASE & AUTH ---
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  firebase_storage: ^13.0.1
  firebase_crashlytics: ^5.0.1
  firebase_analytics: ^12.0.1
  firebase_app_check: ^0.4.0+1
  google_sign_in: ^7.2.0
  sign_in_with_apple: ^7.0.1
  cloud_functions: ^6.0.1

  # --- LOCAL DATABASE ---
  isar: 3.1.0+1
  isar_flutter_libs: 3.1.0+1
  path_provider: ^2.1.4

  # --- MEDIA & UTILS ---
  image_picker: ^1.1.2
  audioplayers: ^6.5.1
  record: ^6.1.1
  video_player: ^2.8.3
  flutter_local_notifications: ^19.4.2
  timezone: ^0.10.1
  
  # --- API & NETWORKING ---
  spotify: ^0.13.7
  http: ^1.2.1
  
  # --- UI & HELPERS ---
  intl: ^0.20.2
  google_fonts: ^6.2.1
  url_launcher: ^6.3.0
  device_info_plus: ^12.1.0
  collection: ^1.17.0
  country_picker: ^2.0.20
  path: ^1.8.3
  provider: ^6.0.0  
  html: ^0.15.4
  flutter_dotenv: ^6.0.0
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.2.2
  markdown_widget: ^2.3.2+8
  encrypt: ^5.0.3
  flutter_secure_storage: ^9.0.0
  pointycastle: ^3.7.4
  uuid: ^4.3.3
  connectivity_plus: ^7.0.0
  in_app_purchase: ^3.1.13
  flutter_image_compress: ^2.2.0

  # --- НОВЫЕ ЗАВИСИМОСТИ ---
  permission_handler: ^12.0.1       # Для запроса разрешений
  cached_network_image: ^3.3.1     # Для кэширования изображений
  flutter_cache_manager: ^3.3.1
  receive_sharing_intent: ^1.4.5   # ДОБАВЛЕНО: для приёма медиа
  
  # --- НОВЫЕ ЗАВИСИМОСТИ ДЛЯ ЭКСПОРТА ---
  pdf: ^3.10.8
  printing: ^5.12.0
  qr_flutter: ^4.1.0
  share_plus: ^12.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.11
  isar_generator: 3.1.0+1
  mockito: ^5.4.4
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter:
  generate: true # This line enables the l10n code generator

  uses-material-design: true

  assets:
    - assets/
    - assets/logo.png
    - assets/google_logo.png
    - assets/apple_logo.png
    - assets/fonts/
    - assets/sounds/
    - assets/music/
    - assets/legal/

  fonts:
    - family: Orbitron
      fonts:
        - asset: assets/fonts/Orbitron-Regular.ttf
        - asset: assets/fonts/Orbitron-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
